### ISSUE TITLE
I got an error to test temBERTure_TM 

### ISSUE THREAD

**Issue by YaldaAmidi227** [ibmm-unibe-ch/TemBERTure#3]
Hi, 

I could run "temBERTure_CLS" correctly and got the same results you shared in Readme but to test "temBERTure_TM" using the same seq that you put in Readme part I got this error: 

In [1]: model_replica3.predict([seq]) %I tested model_replica 1 and 2 and the error was same
  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:01<00:00,  1.24s/it]
Predicted thermal class: Non-thermophilic
Out[1]: ---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In [12], [line 1](vscode-notebook-cell:?execution_count=12&line=1)
----> [1](vscode-notebook-cell:?execution_count=12&line=1) model_replica3.predict([seq])

File [./temBERTure.py:61](https://vscode-remote+ssh-002dremote-002bgrid2.vscode-resource.vscode-cdn.net//temBERTure.py:61), in TemBERTure.predict(self, input_texts)
     [59](https://vscode-remote+ssh-002dremote-002bgrid2.vscode-resource.vscode-cdn.net//temBERTure.py:59) status = 'Thermophilic' if y_preds[0] == 1 else 'Non-thermophilic'
     [60](https://vscode-remote+ssh-002dremote-002bgrid2.vscode-resource.vscode-cdn.net//temBERTure.py:60) print('Predicted thermal class:', status)
---> [61](https://vscode-remote+ssh-002dremote-002bgrid2.vscode-resource.vscode-cdn.net//temBERTure.py:61) print('Thermophilicity prediction score:', preds[0])
     [63](https://vscode-remote+ssh-002dremote-002bgrid2.vscode-resource.vscode-cdn.net//temBERTure.py:63) return [status,preds[0]]

**UnboundLocalError: local variable 'preds' referenced before assignment**

could you please share the output of model_replica3.predict([seq]) in README too. I'm not sure what is the problem. 
Many thanks for sharing your code

**Comment by Ch-rode** [comment]
Dear @YaldaAmidi227, everything should now work correctly if you download TemBERTure again. I have also updated the main README. Please take a look and let me know!

**Comment by YaldaAmidi227** [comment]
> Dear @YaldaAmidi227, everything should now work correctly if you download TemBERTure again. I have also updated the main README. Please take a look and let me know!

I still have the same error "**UnboundLocalError: local variable 'preds' referenced before assignment**" could you please share the output of this line "model_replica2.predict([seq])" ? 

I successfully run the model using these lines :

model_replica2 = TemBERTure(
    adapter_path='./temBERTure/temBERTure_TM/replica2/',  # Path to the adapter for replica 2
    device='cuda',                                        # Device to run the model on
    batch_size=16,                                        # Batch size for inference
    task='regression'                                     # Task type (e.g., regression for TemBERTureTM)
)

but there is an error to report the estimated Tm. 
Thanks for taking the time

**Comment by YaldaAmidi227** [comment]
I wanted to complete my comment. I changed "task" to "classification" instead of "regression" and the code correctly run. the output is: 

                In [1]: model_replica1.predict([seq])
                  0%|          | 0/1 [00:00<?, ?it/s]
                100%|██████████| 1/1 [00:01<00:00,  1.23s/it]
                Predicted thermal class: Thermophilic
                
                Out [1]:
                Thermophilicity prediction score: 1.0
                ['Thermophilic', 1.0]

but when I selected the "regression" **it has this error "UnboundLocalError: local variable 'preds' referenced before assignment**"

**Comment by Ch-rode** [comment]
Dear @YaldaAmidi227,
did you download the repo again? [This](https://github.com/ibmm-unibe-ch/TemBERTure/tree/main/temBERTure) updated version of temBERTure.py should solve your issue. 
![image](https://github.com/user-attachments/assets/ca8eb56d-09d7-41df-bab7-f25765f0f47b)

**Comment by YaldaAmidi227** [comment]
> Dear @YaldaAmidi227, did you download the repo again? [This](https://github.com/ibmm-unibe-ch/TemBERTure/tree/main/temBERTure) updated version of temBERTure.py should solve your issue. ![image](https://private-user-images.githubusercontent.com/61243245/352243564-ca8eb56d-09d7-41df-bab7-f25765f0f47b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzEzNjgsIm5iZiI6MTcyMTkzMTA2OCwicGF0aCI6Ii82MTI0MzI0NS8zNTIyNDM1NjQtY2E4ZWI1NmQtMDlkNy00MWRmLWJhYjctZjI1NzY1ZjBmNDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE4MTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNGFiN2JhOGViZTJiNzBiNGJkMmY5NDY1MzkxNDgwOTYxM2I4MzQ4ZjY0MGQ2MGNlNDg4ODc5ODczZmFjZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MgBhOkYAGi946QqkP7ncf4MgzmRq2-zEwBIepqXyeI0)

Great it works now. Thank you so much

**Comment by Ch-rode** [comment]
Thanks for bringing this up!
